apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
spec:
  serviceAccountName: jenkins
  containers:
    - name: jnlp
      image: masec11112020/jenkins-docker-agent:latest
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      env:
        - name: JENKINS_URL
          value: "http://jenkins.jenkins.svc.cluster.local:8080/"
        - name: JENKINS_TUNNEL
          value: "jenkins-agent.jenkins.svc.cluster.local:50000"
        - name: JENKINS_AGENT_WORKDIR
          value: "/home/jenkins/agent"
      securityContext:
        runAsUser: 0
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: workspace-volume

    - name: docker
      image: docker:20.10.24-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"
      volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-graph-storage
        - mountPath: /home/jenkins/agent
          name: workspace-volume
        - mountPath: /var/run
          name: docker-sock

    - name: kubectl
      image: alpine/k8s:1.25.14
      command: ['cat']
      tty: true
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: workspace-volume
        - mountPath: /var/run
          name: docker-sock

  volumes:
    - name: docker-graph-storage
      emptyDir: {}
    - name: workspace-volume
      emptyDir: {}
    - name: docker-sock
      emptyDir: {}
      
  restartPolicy: Never 
