/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/CustomsPlate/Calc/ActionButton.vue')['default']
    ActionCell: typeof import('./src/components/table/ActionCell.vue')['default']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    CalcPlate: typeof import('./src/components/CustomsPlate/Calc/CalcPlate.vue')['default']
    CalcPopp: typeof import('./src/components/CustomsPlate/Calc/CalcPopp.vue')['default']
    CheckBoxComponent: typeof import('./src/components/sharedComponents/CheckBoxComponent.vue')['default']
    CustomsPlateCacl: typeof import('./src/components/CustomsPlate/Calc/CustomsPlateCacl.vue')['default']
    DateRangeSelector: typeof import('./src/components/table/DateRangeSelector.vue')['default']
    DocumentHeader: typeof import('./src/components/CustomsPlate/Calc/DocumentHeader.vue')['default']
    DocumentsOptions: typeof import('./src/components/auth/Doc/DocumentsOptions.vue')['default']
    ExtensionsCustomOffline: typeof import('./src/components/CustomsPlate/ExtensionsCustomOffline.vue')['default']
    FormComponent: typeof import('./src/components/auth/Login/formComponent.vue')['default']
    HorizontalNavbar: typeof import('./src/components/auth/Layouts/HorizontalNavbar.vue')['default']
    PageButton: typeof import('./src/components/table/PageButton.vue')['default']
    PricingDetails: typeof import('./src/components/CustomsPlate/Calc/PricingDetails.vue')['default']
    ReportsTable: typeof import('./src/components/table/ReportsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsCard: typeof import('./src/components/table/StatisticsCard.vue')['default']
    StatisticsSection: typeof import('./src/components/table/StatisticsSection.vue')['default']
    SyncLoader: typeof import('./src/components/SyncLoader.vue')['default']
    TablePagination: typeof import('./src/components/table/TablePagination.vue')['default']
    TableView: typeof import('./src/components/table/TableView.vue')['default']
    TabNavigation: typeof import('./src/components/table/TabNavigation.vue')['default']
    Total: typeof import('./src/components/CustomsPlate/Calc/Total.vue')['default']
    VehicleTypeOffline: typeof import('./src/components/CustomsPlate/VehicleTypeOffline.vue')['default']
    VerticalNavbar: typeof import('./src/components/auth/Layouts/VerticalNavbar.vue')['default']
  }
}
